/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <zp50_items>
#include <zmvip>

#define PLUGIN "Toxic (Item)"
#define VERSION "1.0"
#define AUTHOR "Administrator"

new It, TotalLimit = 2, iLimit
native zp_toxic_m4(id)
native zp_has_toxic_m4(id)
public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_event("HLTV", "event_round_start", "a", "1=0", "2=0");		
	It = zp_items_register("Toxic M4A1", "",60)
}
public event_round_start()
	iLimit = 0
public zp_fw_items_select_pre(player, itemid)
{
	if(itemid!=It)
		return ZP_ITEM_AVAILABLE
	
	if(zp_core_is_zombie(player))
		return ZP_ITEM_DONT_SHOW
	
	if(zp_has_toxic_m4(player) == 2)
		return ZP_ITEM_NOT_AVAILABLE
	if(zv_get_user_flags(player) & ZV_MAIN)
		return ZP_ITEM_AVAILABLE
	new Txt[32]
	formatex(Txt, charsmax(Txt),"[%d/%d]",iLimit,TotalLimit)
	if(iLimit >= TotalLimit)
		return ZP_ITEM_NOT_AVAILABLE
	return ZP_ITEM_AVAILABLE
}

public zp_fw_items_select_post(player, itemid)
{
	if ( itemid == It )
	{
		zp_toxic_m4(player)
		iLimit++
	}
}